all: dora-mesh stigmergy hop-count

dora-mesh: dora-mesh.bzz
	bzzc -I /usr/local/share/buzz/include dora-mesh.bzz

stigmergy: stigmergy.bzz
	bzzc -I /usr/local/share/buzz/include stigmergy.bzz

hop-count: hop-count.bzz
	bzzc -I /usr/local/share/buzz/include hop-count.bzz

clean:
	rm *.bo *.bdb
